---
# tasks file for app
        
  - name: Refresh subscription manager
    command: subscription-manager refresh 

  - name: clean yum cache
    command: 
      cmd: /bin/yum clean all
      warn: false 

  - name: download node
    shell: curl -sL https://rpm.nodesource.com/setup_14.x | sudo -E bash -

  - name: Install nodejs
    yum:
      name: nodejs
      update_cache: yes

  - name: Create a directory if it does not exist
    ansible.builtin.file:
      path: "{{ node_apps_location }}"
      state: directory
      mode: '0755'

  - name: "{{ nexusrm_location }} into {{ node_apps_location }}"
    ansible.builtin.unarchive:
      src: "{{ nexusrm_location }}"
      dest: "{{ node_apps_location }}"
      remote_src: yes
      
  - name: Install packages based on package.json.
    npm:
      path: "{{ node_apps_location }}/{{ file_name_unarchive }}"

  - name: setting app as executable
    file: dest={{ node_apps_location }}/{{ file_name_unarchive }}/index.js mode=a+x

  - name: make myapp.service
    blockinfile:
      dest: /lib/systemd/system/myapp.service
      block: |
        [Unit]
        Description=My app
        [Service]
        Restart=always
        RestartSec=5
        ExecStart=/usr/bin/node {{ node_apps_location }}/{{ file_name_unarchive }}
        User=root
        Environment=TARGET_URL=HTTP://{{ target_url }}.{{ domain_name }}.{{ domain_name_extension }}
        Environment=PORT={{ port_number }}
        WorkingDirectory={{ node_apps_location }}/{{ file_name_unarchive }}
        [Install]
        WantedBy=multi-user.target
      insertafter: EOF
      create: yes

  - name: permit open traffic on port 80/tcp
    ansible.posix.firewalld:
      port: 80/tcp
      permanent: yes
      state: enabled

  - name: reload service firewalld
    systemd:
      name: firewalld
      state: reloaded

  - name: daemon-reload
    ansible.builtin.systemd:
      daemon_reload: yes

  - name: enable reloading myapp.service
    service:
      name: myapp
      enabled: yes

  - name: reloading myapp.service
    service:
      name: myapp
      state: restarted

